trigger:
- master

pool:
  name: Default
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)'
    contents: 'package.json' 
    targetFolder: $(System.DefaultWorkingDirectory)
  displayName: 'Copy package.json'   
 
    
- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'

- task: PublishBuildArtifacts@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/npm'
    artifactName: npm
  displayName: 'Publish npm artifact'
